# Generated by Django 6.1.1 on 2026-09-23 10:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Название')),
                ('kind', models.CharField(choices=[('home', 'Недвижимость'), ('car', 'Автомобили'), ('food', 'Продукты'), ('goods', 'Товары и опт')], max_length=12, verbose_name='Категория')),
                ('description', models.TextField(max_length=5000, verbose_name='Описание')),
                ('region', models.CharField(max_length=100, verbose_name='Город или регион')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена за единицу, ₸')),
                ('stock', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10000000)], verbose_name='Остаток, единиц')),
                ('unit', models.CharField(default='шт.', max_length=20, verbose_name='Единица измерения')),
                ('lead_days', models.PositiveSmallIntegerField(default=7, validators=[django.core.validators.MaxValueValidator(365)], verbose_name='Срок пополнения, дней')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('is_demo', models.BooleanField(default=False, verbose_name='Демонстрационный пример')),
                ('demo_key', models.CharField(blank=True, editable=False, max_length=40, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Товар или объект',
                'verbose_name_plural': 'Товары и объекты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена за единицу, ₸')),
                ('sold', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10000000)], verbose_name='Продано за день')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='market.product')),
            ],
            options={
                'verbose_name': 'День продаж',
                'verbose_name_plural': 'История цен и продаж',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='market.product')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('buyer', 'Покупатель'), ('seller', 'Продавец')], default='buyer', max_length=10, verbose_name='Роль')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('comment', models.TextField(max_length=2000, verbose_name='Ваш опыт использования')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Скрыт модератором')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='market.product')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('assistant', 'Помощник')], max_length=10)),
                ('content', models.TextField(max_length=6000)),
                ('source', models.CharField(blank=True, max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата')),
                ('direction', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=10, verbose_name='Тип операции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма, ₸')),
                ('category', models.CharField(choices=[('sales', 'Продажи'), ('purchase', 'Покупки'), ('advertising', 'Реклама'), ('delivery', 'Доставка'), ('rent', 'Аренда'), ('salary', 'Зарплата'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория')),
                ('note', models.CharField(max_length=250, verbose_name='Описание')),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Денежная операция',
                'verbose_name_plural': 'Доходы и расходы',
                'ordering': ['-date', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='market_positive_amount')],
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='market_positive_price'),
        ),
        migrations.AddConstraint(
            model_name='observation',
            constraint=models.UniqueConstraint(fields=('product', 'date'), name='market_one_observation_daily'),
        ),
        migrations.AddConstraint(
            model_name='observation',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='market_observation_positive_price'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='market_unique_favorite'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('product', 'author'), name='market_one_review_per_user'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='market_valid_rating'),
        ),
    ]
