# Generated by Django 6.1.1 on 2026-09-23 11:30

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brief',
            field=models.JSONField(blank=True, default=dict, verbose_name='Характеристики и разбор'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_path',
            field=models.CharField(blank=True, max_length=250, validators=[django.core.validators.RegexValidator('^catalog-photos/[a-z0-9-]+\\.jpg$', 'Укажите файл catalog-photos/имя.jpg.')], verbose_name='Фото из каталога'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_reference',
            field=models.BooleanField(default=False, verbose_name='Обзорная карточка'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo_key',
            field=models.CharField(blank=True, editable=False, max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='kind',
            field=models.CharField(choices=[('home', 'Недвижимость'), ('car', 'Автомобили'), ('food', 'Продукты'), ('goods', 'Товары и опт'), ('electronics', 'Электроника')], max_length=12, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена за единицу, ₸'),
        ),
    ]
