# Generated by Django 6.1.1 on 2026-09-23 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('business_type', models.CharField(choices=[('retail', 'Торговля (продажи товаров)'), ('services', 'Услуги (записи клиентов)')], default='retail', max_length=20, verbose_name='Тип бизнеса')),
                ('region', models.CharField(max_length=100, verbose_name='Регион')),
                ('lead_time_weeks', models.PositiveSmallIntegerField(default=3, help_text='Сколько недель занимает поставка товара или подготовка смен.', verbose_name='Срок подготовки, недель')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendations', models.JSONField(blank=True, default=dict)),
                ('recommendations_source', models.CharField(blank=True, choices=[('ai', 'ИИ (Claude)'), ('rules', 'Правила')], max_length=10)),
                ('recommendations_note', models.CharField(blank=True, max_length=300)),
                ('recommendations_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='forecast.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=120)),
                ('quantity', models.FloatField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='forecast.dataset')),
            ],
            options={
                'indexes': [models.Index(fields=['dataset', 'category', 'date'], name='forecast_re_dataset_6cd480_idx')],
            },
        ),
    ]
